### ISSUE TITLE
Doesn't work with SSR due to insistence on using window object

### ISSUE THREAD

**Issue by CoenWarmer** [dvtng/react-loading-skeleton#2]
Unfortunately, in SSR contexts the server side renderer will crash due to it using the window object which is not available in the Node context.

**Comment by CoenWarmer** [comment]
Will attempt a PR if time permits.

**Comment by rajatjasuja23** [comment]
Can u please provide the code for ssr

**Comment by camdagr8** [comment]
Any movement on this yet?

**Comment by hsingh23** [comment]
Yup - I have the same issue

**Comment by Soundvessel** [comment]
Same issue with Nextjs which uses SSR.

```
{ ReferenceError: window is not defined
    at X:\WSProjects\Expensify2\node_modules\react-loading-skeleton\dist\bundle.js:407:2
    at X:\WSProjects\Expensify2\node_modules\react-loading-skeleton\dist\bundle.js:396:46
    at module.exports (X:\WSProjects\Expensify2\node_modules\react-loading-skeleton\dist\bundle.js:441:46)
    at Object.stylesInDom (X:\WSProjects\Expensify2\node_modules\react-loading-skeleton\dist\bundle.js:365:36)
    at __webpack_require__ (X:\WSProjects\Expensify2\node_modules\react-loading-skeleton\dist\bundle.js:30:30)
    at Object.defineProperty.value (X:\WSProjects\Expensify2\node_modules\react-loading-skeleton\dist\bundle.js:112:1)
    at __webpack_require__ (X:\WSProjects\Expensify2\node_modules\react-loading-skeleton\dist\bundle.js:30:30)
    at Object.<anonymous> (X:\WSProjects\Expensify2\node_modules\react-loading-skeleton\dist\bundle.js:839:18)
    at __webpack_require__ (X:\WSProjects\Expensify2\node_modules\react-loading-skeleton\dist\bundle.js:30:30)
    at module.exports (X:\WSProjects\Expensify2\node_modules\react-loading-skeleton\dist\bundle.js:76:18)
    at X:\WSProjects\Expensify2\node_modules\react-loading-skeleton\dist\bundle.js:79:10
    at webpackUniversalModuleDefinition (X:\WSProjects\Expensify2\node_modules\react-loading-skeleton\dist\bundle.js:3:20)
    at Object.<anonymous> (X:\WSProjects\Expensify2\node_modules\react-loading-skeleton\dist\bundle.js:10:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32) sourceMapsApplied: true }
```

**Comment by UNLRN** [comment]
@dvtng I submitted a PR for adding SSR support here #12 
Comments or potential other solutions are welcome.

**Comment by icharge** [comment]
![image](https://user-images.githubusercontent.com/1619007/44247057-ed0a1100-a20b-11e8-9e5b-5d97c19381f6.png)
I got Skeleton is not defined

**Comment by dvtng** [comment]
Sorry it took me a long time to get to this. I've just released 0.6.0 which uses Emotion under the hood to support SSR. If you already use Emotion for your own CSS, then great -- it'll just work for you. Otherwise, please see Emotion docs for how to enable SSR: https://emotion.sh/docs/ssr.

**Comment by MatteoGioioso** [comment]
With `nextjs` you can use `dynamic import` and import `react-skeleton-loader` into `componentDidMount`

**Comment by jmayergit** [comment]
> With `nextjs` you can use `dynamic import` and import `react-skeleton-loader` into `componentDidMount` so the `window` object will be available

I wonder if we should be using skeletons and SSR. If a page loads with data then there is not waiting for data.

**Comment by jmayergit** [comment]
> With `nextjs` you can use `dynamic import` and import `react-skeleton-loader` into `componentDidMount` so the `window` object will be available

If the page is rendered on the server then there is no need for skeletons, I think.

**Comment by MatteoGioioso** [comment]
@jmayergit Well it depends on your use case. You might not want to server render everything. 
Example: an infinite scroll list

**Comment by jmayergit** [comment]
Or if you fetch data client side, I think.

**Comment by MatteoGioioso** [comment]
Exactly =)

**Comment by jmayergit** [comment]
> With `nextjs` you can use `dynamic import` and import `react-skeleton-loader` into `componentDidMount` so the `window` object will be available

I am unable to get this working.

```
  componentDidMount() {
    const Skeleton = dynamic(() => import('react-loading-skeleton'));
  }
```

Can you provide an examaple?

**Comment by MatteoGioioso** [comment]
Try this

You can make an helper method in a class based component
```
 importDynamicComponents() {
    this.Skeleton = dynamic(() => import("react-loading-skeleton"));
  }
```
then call it when you are on the client
```
componentDidMount() {
    this.importDynamicComponents();
}
```

The render it
```
render(){
<this.Skeleton>
  //children
</this.Skeleton>
}
```

I hope this helps, let me know

**Comment by vnugent** [comment]
I'm seeing this issue with Gatsby. Do you have any workarounds?

**Comment by pi0neerpat** [comment]
@vnugent This fixed it for me!
https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules
